### ISSUE TITLE
Bad data passed to solver

### ISSUE THREAD

**Issue by timholy** [tkoolen/Parametron.jl#80] opened 2018-09-25 15:42 UTC
I'm seeing errors like the following frequently, and before diving in I'm curious to know if others have seen the same:

```julia
ERROR: LoadError: Gurobi.GurobiError(10003, "Element 1 of a double array is Nan.")
Stacktrace:
 [1] add_constrs!(::Gurobi.Model, ::Array{Int32,1}, ::Array{Int32,1}, ::Array{Float64,1}, ::Array{Int8,1}, ::Array{Float64,1}) at /home/tim/.julia/dev/Gurobi/src/grb_constrs.jl:63
 [2] add_constrs!(::Gurobi.Model, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,1}, ::Array{Int8,1}, ::Array{Float64,1}) at /home/tim/.julia/dev/Gurobi/src/grb_constrs.jl:71
 [3] add_linear_constraints! at /home/tim/.julia/dev/Gurobi/src/MOIWrapper.jl:131 [inlined]
 [4] add_linear_constraint(::Gurobi.Optimizer, ::MathOptInterface.VectorAffineFunction{Float64}, ::Int8) at /home/tim/.julia/packages/LinQuadOptInterface/WqyOh/src/constraints/vectoraffine.jl:58
 [5] addconstraint!(::Gurobi.Optimizer, ::MathOptInterface.VectorAffineFunction{Float64}, ::MathOptInterface.Nonnegatives) at /home/tim/.julia/packages/LinQuadOptInterface/WqyOh/src/constraints/vectoraffine.jl:12
 [6] copyconstraints!(::Gurobi.Optimizer, ::Parametron.ParametronMOIModel{Float64}, ::Bool, ::MathOptInterface.Utilities.IndexMap, ::Type{MathOptInterface.VectorAffineFunction{Float64}}, ::Type{MathOptInterface.Nonnegatives}) at /home/tim/.julia/packages/MathOptInterface/QfYLx/src/Utilities/copy.jl:78
 [7] defaultcopy!(::Gurobi.Optimizer, ::Parametron.ParametronMOIModel{Float64}, ::Bool) at /home/tim/.julia/packages/MathOptInterface/QfYLx/src/Utilities/copy.jl:111
 [8] #copy!#71 at /home/tim/.julia/packages/LinQuadOptInterface/WqyOh/src/copy.jl:5 [inlined]
 [9] copy! at /home/tim/.julia/packages/LinQuadOptInterface/WqyOh/src/copy.jl:4 [inlined]
 [10] initialize!(::Parametron.Model{Float64,Gurobi.Optimizer}) at /home/tim/.julia/dev/Parametron/src/model.jl:114
 [11] solve! at /home/tim/.julia/dev/Parametron/src/model.jl:149 [inlined]
 [12] #fit_quadratic_lowerbound!#57(::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Function, ::CoordinateSplittingPTrees.SymmetricArray{Float64,2,Array{Float64,2}}, ::getfield(CoordinateSplittingPTrees, Symbol("#updater#54")){typeof(value),Int64,Int64,DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering},getfield(CoordinateSplittingPTrees, Symbol("#maybe_enqueue#53")){DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering}},CoordinateSplittingPTrees.SymmetricArray{Float64,2,Array{Float64,2}},Array{Float64,1},Array{Float64,1},Array{Bool,1},Array{Float64,2},Array{Float64,2},Array{Float64,2},Array{Float64,1}}, ::Parametron.Model{Float64,Gurobi.Optimizer}, ::Array{Parametron.Functions.Variable,1}, ::Array{Parametron.Functions.Variable,1}, ::Box{2,Float64,Float64,3,Float64,Interval{Float64}}, ::Array{Float64,1}) at /home/tim/.julia/dev/CoordinateSplittingPTrees/src/cs2.jl:472
 [13] (::getfield(CoordinateSplittingPTrees, Symbol("#kw##fit_quadratic_lowerbound!")))(::NamedTuple{(:X, :X2, :Δf),Tuple{Array{Float64,2},Array{Float64,2},Array{Float64,1}}}, ::typeof(CoordinateSplittingPTrees.fit_quadratic_lowerbound!), ::CoordinateSplittingPTrees.SymmetricArray{Float64,2,Array{Float64,2}}, ::Function, ::Parametron.Model{Float64,Gurobi.Optimizer}, ::Array{Parametron.Functions.Variable,1}, ::Array{Parametron.Functions.Variable,1}, ::Box{2,Float64,Float64,3,Float64,Interval{Float64}}, ::Array{Float64,1}) at ./none:0 (repeats 2 times)
 [14] (::getfield(OptimizeIVQ, Symbol("#newton#7")){typeof(f),Box{2,Float64,Float64,3,Float64,Interval{Float64}},World{Float64,Float64,Float64},DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering},DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering},getfield(OptimizeIVQ, Symbol("#addqueues_iv#4")){typeof(f),getfield(OptimizeIVQ, Symbol("#addqueues#3")){DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering},DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering}}},getfield(CoordinateSplittingPTrees, Symbol("#updater#54")){typeof(value),Int64,Int64,DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering},getfield(CoordinateSplittingPTrees, Symbol("#maybe_enqueue#53")){DataStructures.PriorityQueue{Box{2,Float64,Float64,3,Float64,Interval{Float64}},Float64,Base.Order.ForwardOrdering}},CoordinateSplittingPTrees.SymmetricArray{Float64,2,Array{Float64,2}},Array{Float64,1},Array{Float64,1},Array{Bool,1},Array{Float64,2},Array{Float64,2},Array{Float64,2},Array{Float64,1}},Parametron.Model{Float64,Gurobi.Optimizer},Array{Parametron.Functions.Variable,1},Array{Parametron.Functions.Variable,1},Array{Float64,2},Array{Float64,2},Array{Float64,1}})(::Float64) at /home/tim/.julia/dev/OptimizeIVQ/src/OptimizeIVQ.jl:78
 [15] #minimize#1(::Int64, ::Float64, ::Int64, ::Function, ::typeof(f), ::Box{2,Float64,Float64,3,Float64,Interval{Float64}}) at /home/tim/.julia/dev/OptimizeIVQ/src/OptimizeIVQ.jl:111
 [16] (::getfield(OptimizeIVQ, Symbol("#kw##minimize")))(::NamedTuple{(:nfit, :showprogress),Tuple{Int64,Int64}}, ::typeof(minimize), ::Function, ::Box{2,Float64,Float64,3,Float64,Interval{Float64}}) at ./none:0
 [17] top-level scope at none:0
 [18] include at ./boot.jl:317 [inlined]
 [19] include_relative(::Module, ::String) at ./loading.jl:1041
 [20] include at ./sysimg.jl:29 [inlined]
 [21] includet(::String) at /home/tim/.julia/dev/Revise/src/Revise.jl:532
 [22] top-level scope at none:0
in expression starting at /home/tim/data/interval_registration/ireg2.jl:104
```

I added some debugging output like this:
```sh
tim@diva:~/.julia/dev/Gurobi$ git diff
diff --git a/src/grb_attrs.jl b/src/grb_attrs.jl
index 2a2a591..69712be 100644
--- a/src/grb_attrs.jl
+++ b/src/grb_attrs.jl
@@ -304,6 +304,7 @@ function set_dblattrarray!(model::Model, name::String, start::Integer, len::Inte
     ret = @grb_ccall(setdblattrarray, Cint,
         (Ptr{Cvoid}, Ptr{UInt8}, Cint, Cint, Ptr{Float64}), model, name, start-1, len, fvec(values))
     if ret != 0
+        @show name values
         throw(GurobiError(model.env, ret))
     end
     nothing
diff --git a/src/grb_constrs.jl b/src/grb_constrs.jl
index c78febe..0bc79dd 100644
--- a/src/grb_constrs.jl
+++ b/src/grb_constrs.jl
@@ -60,6 +60,7 @@ function add_constrs!(model::Model, cbegins::IVec, inds::IVec, coeffs::FVec, rel
             rel, rhs, C_NULL)
 
         if ret != 0
+            @show cbegins inds coeffs rel rhs
             throw(GurobiError(model.env, ret))
         end
     end
```
 (and I'm pretty sure I've seen the same kind of error with GLPK), with the following result:
```julia
cbegins = Int32[1, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85]
inds = Int32[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
coeffs = [6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310, 6.91268e-310, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 6.91266e-310]
rel = Int8[62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62]
rhs = [2.06668e-320, NaN, 9.88131e-324, 6.91268e-310, 6.91268e-310, 6.91266e-310, 6.91266e-310, 1.4822e-323, 9.88131e-324, 6.91268e-310, 6.91268e-310, -0.0, 6.91268e-310, 6.91266e-310, 6.91266e-310]
```
Looks like the C code is getting junk passed to it, perhaps just for the `Float64` values.

I am using a slightly unconventional parameter-updating strategy (see https://github.com/tkoolen/Parametron.jl/issues/67#issuecomment-423745932), but I've verified via a `try/catch` block that when this error is thrown, the values in the Julia arrays that "back" the `Parameter`s are perfectly normal-seeming, e.g.,
```julia
X = [0.0 0.0 0.0; 0.0 4.93827 0.0; 0.0 4.93827 -0.148148; -14.8148 4.93827 0.0; 0.0 -14.8148 0.0; 0.0 -14.8148 0.0; -14.8148 4.93827 -0.148148; 0.0 -14.8148 0.444444; 0.0 -14.8148 0.444444; 0.0 -14.8148 0.444444; -14.8148 -14.8148 0.444444; 0.0 0.0 0.444444; 0.0 -29.6296 0.444444; 0.0 4.93827 0.444444; -14.8148 -29.6296 0.444444]
X2 = [0.0 0.0 0.0; 0.0 12.1933 0.0; 0.0 12.1933 0.0109739; 109.739 12.1933 0.0; 0.0 109.739 0.0; 0.0 109.739 0.0; 109.739 12.1933 0.0109739; 0.0 109.739 0.0987654; 0.0 109.739 0.0987654; 0.0 109.739 0.0987654; 109.739 109.739 0.0987654; 0.0 0.0 0.0987654; 0.0 438.957 0.0987654; 0.0 12.1933 0.0987654; 109.739 438.957 0.0987654]
Δf = [0.0, 0.00402906, 0.0354306, 0.0369546, 0.0384715, 0.0384715, 0.0683561, 0.0830869, 0.0830869, 0.0830869, 0.0350268, 0.0943551, 0.0772324, 0.0983842, 0.0291723]
```

**Comment by tkoolen** [comment] 2018-09-25 17:33
Do you have any integer constraints / can you reproduce the problem without integer constraints? If so, could you try with OSQP? Both GLPK and Gurobi are based on LinQuadOptInterface, while the OSQP Julia wrapper is more of its own thing, so this would be a good test to see whether it's a problem in Parametron or LinQuadOptInterface/GLPK/Gurobi.

**Comment by tkoolen** [comment] 2018-09-25 17:34
Also, could you provide instructions for how to reproduce the issue?

**Comment by timholy** [comment] 2018-09-27 00:33
Hmm, I was getting this all the time, so I wondered if it was common. Sounds like the answer is "no."

I changed a couple of things and now it's not happening :fireworks:. One change is that I've updated to the latest release of Parametron; I also changed my data-passing strategy to explicitly look for cases of degeneracy. Interestingly, in the case above it is a degenerate problem (`A = [X X2]` has one zero singular value), so if I had to bet that's the crucial change. However, my attempt to replicate this failed:
```julia
using Parametron, Gurobi, Random

model = Model(Gurobi.Optimizer())
x = [Variable(model) for _ = 1:2]
rhs = Parameter(rand!, zeros(2), model)
row = rand(2)'
A = [row; row]
Ap = Parameter(model; val=A)
@constraint(model, A*x >= rhs)
@objective(model, Minimize, sum(A*x))
solve!(model)
```
doesn't throw the error I reported above.

So I'm a bit at a loss, but certainly there is no point worrying about this until I can come up with a replicable test case.

**Comment by tkoolen** [comment] 2018-09-27 00:59
The latest release being 0.2.0 or 0.3.0 (https://github.com/JuliaLang/METADATA.jl/pull/18425, not yet merged)?

**Comment by timholy** [comment] 2018-09-27 01:02
Sorry...master branch, which will become 0.3.0.

**Comment by tkoolen** [comment] 2018-09-27 01:03
(Sorry I accidentally closed this for a second earlier; reopened after you closed this because I'd still like to get to the bottom of this.)

**Comment by timholy** [comment] 2018-09-27 01:03
OK. I'll be on the lookout and try to isolate a testcase if I find it again. My currently code involves a large mix of public and private repos so is non-trivial to distill down to something simple.

**Comment by tkoolen** [comment] 2018-12-05 19:58
I think I'll close this for lack of a reproducible example now. Feel free to reopen if you do find one.

**Closed as completed by tkoolen** 2018-12-05 19:58 UTC
